#!/bin/sh
gf -src --gfo-dir=bin -make -literal=Symb InstrucsEngRGL.gf InstrucsSweRGL.gf InstrucsEngConcat.gf InstrucsSolr.gf
gf -src --gfo-dir=bin -make -literal=Symb Vasttrafik.gf VasttrafikEngConcat.gf VasttrafikApi.gf
cp Instrucs.pgf ../nlparser/src/main/resources/
cp Instrucs.pgf  ../mock-data/src/main/resources/

cp Vasttrafik.pgf ../nlparser/src/main/resources/
cp Vasttrafik.pgf  ../mock-data/src/main/resources/