#!/bin/sh
/home/vagrant/.cabal/bin/gf -src --gfo-dir=bin -make -literal=Symb InstrucsEngRGL.gf InstrucsSweRGL.gf InstrucsEngConcat.gf InstrucsSolr.gf
/home/vagrant/.cabal/bin/gf -src --gfo-dir=bin -make -literal=Symb Vasttrafik.gf VasttrafikEngConcat.gf VasttrafikApi.gf VasttrafikPL.gf

mkdir -p ../nlparser/src/main/resources
mkdir -p ../mock-data/src/main/resources

cp Instrucs.pgf ../nlparser/src/main/resources/
cp Instrucs.pgf  ../mock-data/src/main/resources/

cp Vasttrafik.pgf ../nlparser/src/main/resources/
cp Vasttrafik.pgf  ../mock-data/src/main/resources/